add task weather
inf-lab-dev/labs pull request #29
Opened 2024-12-30 14:05 UTC by MariusLang

2025-01-01 11:27 UTC, Kuschel-Swein commented
Even though this PR is still a draft (should I review it already?) I'd like to drop some notes:

- I think there are too many tasks, we should maybe move some of them to the bonus tasks. I get the idea that we are literally doing the Mastodon task in a simplified version, but maybe we could tweak it so we get at most like 3 - 4 tasks
- we should really think about the agressive IP blocking over at wttr.in - maybe we should provide some HTTP answers (their JSON) as plain files and provide a "backup function" that uses those cached values, so if GHs codespace is blocked we can still do this task

2025-01-02 08:09 UTC, MariusLang commented
I think 6 subtask are fine here, as they offer a really fine granular description. Sometimes just two lines of code must be written.

2025-01-02 08:16 UTC, MariusLang commented
What do you think about offering a static html file as backup:

```html
<html>

<head>
    <meta name="color-scheme" content="light dark">
</head>

<body>
    <pre style="word-wrap: break-word; white-space: pre-wrap;">Bamberg: 🌧   🌡️+7°C 🌬️→23km/h
</pre>
</body>

</html>
```

2025-01-04 09:51 UTC, Kuschel-Swein requested changes

2025-01-04 09:51 UTC, Kuschel-Swein commented on weather/material/lab-weather.zip
I'd really favour using the new [zip manifest api](https://github.com/inf-lab-dev/page?tab=readme-ov-file#zipjson)

2025-01-04 09:51 UTC, Kuschel-Swein commented on weather/material/make-zip.sh
I'd really favour using the new [zip manifest api](https://github.com/inf-lab-dev/page?tab=readme-ov-file#zipjson)

2025-01-04 09:51 UTC, Kuschel-Swein commented on weather/material/scripts/setup.sh
I'd really favour using the new [zip manifest api](https://github.com/inf-lab-dev/page?tab=readme-ov-file#zipjson)

2025-01-04 09:51 UTC, Kuschel-Swein commented on weather/task.md
> +wget -O - https://inf-lab.dev/weather/material/scripts/setup.sh | bash
Don't forget to update this when using zip manifests

2025-01-04 09:51 UTC, Kuschel-Swein commented on weather/task.md
> +Bamberg: 🌫  🌡️+0°C 🌬️→6km/h
Is this `bash` code?

2025-01-04 09:51 UTC, Kuschel-Swein commented on weather/task.md
> +Bamberg: 🌫  🌡️+0°C 🌬️→6km/h
Is this `bash` code?

2025-01-04 09:51 UTC, Kuschel-Swein commented on weather/task.md
> +Bamberg: 🌫  🌡️+0°C 🌬️→6km/h
Is this `bash` code?

2025-01-04 09:51 UTC, Kuschel-Swein commented on weather/task.md
> +Die gesamte Logik soll innerhalb des Blocks `if __name__ == "__main__":` implementiert werden, um sicherzustellen, dass der Code nur ausgeführt wird, wenn das Skript direkt gestartet wird.
I'd rather use a dedicated `main` function, so we can test it easier using `check50`

2025-01-04 09:51 UTC, Kuschel-Swein commented on weather/task.md
> +## Teilaufgabe 5
I still think this is too much, especially when students have questions for the mastodon task...

2025-01-04 09:51 UTC, Kuschel-Swein commented on weather/task.md
> +- Initialisierung: Beim Erstellen der `TempRangeFilter`-Klasse werden zwei Parameter, `min_temp` und `max_temp`, übergeben. Diese geben den Temperaturbereich an, innerhalb dessen die Städte überprüft
I'd prefer making the keywords at the start of the line **bold:**

2025-01-04 09:51 UTC, Kuschel-Swein commented on weather/task.md
> +Anweisungen um weitere Filter zu implementieren, findest du in den Bonusaufgaben.
"Anweisungen" sounds weird, what about "Aufgaben"?

2025-01-04 09:51 UTC, Kuschel-Swein commented on weather/task.md
> +In dieser Teilaufgabe kombinierst du die Filterlogik aus [Teilaufgabe 5](#teilaufgabe-5) und wendest die implementierten Filter auf die Liste `cities_weather` an. Ziel ist es, die Liste so zu filtern
again, please use a dedicated `main()`

2025-01-04 09:51 UTC, Kuschel-Swein commented on weather/task.md
> +Anschließend iterierst du über die Liste `cities_weather`, die die Wetterdaten der Städte enthält. Für jede Stadt überprüfst du, ob das definierte Filterkriterium erfüllt ist. Wenn eine Stadt den Fil
Last sentence is no german sentence, its missing "ausgegeben werden".

2025-01-04 09:51 UTC, Kuschel-Swein commented on weather/backup-material/bamberg.html
> +        const cityFromPath = window.location.pathname.split('/').filter(Boolean)[0];
This wont run when calling via requests (or other libraries) as JS is executed client side - we could however provide a miniature Flask server.

Also, as I did not find any note about the backup material:
Could you please elaborate on how you are planning to do this?

2025-01-04 09:51 UTC, Kuschel-Swein commented on weather/bonus/filter.md
> +- Initialisierung: Beim Erstellen der `WindRangeFilter`-Klasse werden zwei Parameter, `min_wind` und `max_wind`, übergeben. Diese definieren den Bereich der Windgeschwindigkeit, innerhalb dessen eine
Again, I'd make keywords at the start of the line **bold:**

2025-01-04 09:51 UTC, Kuschel-Swein commented on weather/bonus/filter.md
> +- Methode `evaluate`: Die Methode nimmt ein `CityWeather`-Objekt entgegen und prüft, ob die Windgeschwindigkeit der Stadt innerhalb des angegebenen Bereichs liegt.
Again, I'd make keywords at the start of the line **bold:**

2025-01-04 09:51 UTC, Kuschel-Swein commented on weather/bonus/filter.md
> +- Initialisierung: Beim Erstellen der `ConditionFilter`-Klasse wird ein Parameter `condition` übergeben, der das gesuchte Wetter-Symbol angibt (z. B. "🌫").
Again, I'd make keywords at the start of the line **bold:**

2025-01-04 09:51 UTC, Kuschel-Swein commented on weather/bonus/filter.md
> +- Methode `evaluate`: Diese Methode prüft, ob das Wetter-Symbol des übergebenen `CityWeather`-Objekts mit dem gewünschten Symbol übereinstimmt.
Again, I'd make keywords at the start of the line **bold:**

2025-01-04 09:51 UTC, Kuschel-Swein commented on weather/bonus/filter.md
> +In dieser Teilaufgabe integrierst du die neuen Filter und wendest die sie auf die Liste `cities_weather` an. Ziel ist es, die Liste so zu filtern, dass nur die Städte übrig bleiben, die den angegeben
Again, I'd use `main()`

2025-01-04 09:51 UTC, Kuschel-Swein commented on weather/bonus/index.md
> +Hier können weitere Aufgaben zum [Aufgabenliste Lab](../) gefunden werden.
This info still references "Aufgabenliste" not "Wetter"

2025-01-04 09:51 UTC, Kuschel-Swein commented on weather/task.md
> +**Disclaimer:** Diese Aufgabe wurde nicht vom Lehrstuhl herausgegeben und kann Fehler enthalten. Sie dient, wie das gesamte Material von [inf-lab.dev](https://inf-lab.dev), lediglich zu Übungszwecken
I'd love to somewhere reference that this task was inspired by a (prior) module of the chair

2025-01-04 10:02 UTC, Kuschel-Swein commented
A sample zip manifest could look like this:

Put it in `lab-weather.zip.json`, then the URL to the sh file is at `<URL_PATH_TO_MANIFEST_FILE>/lab-weather.zip.sh` and the zip just omits the `sh` suffix.

```json
{
    "include": ["template/city_weather.py", "template/filter.py", "template/main.py"],
    "self_extraction": {
        "post_user_commands": ["cd lab-weather", "code main.py"]
    }
}
```

2025-01-04 10:11 UTC, MariusLang commented on weather/task.md
> +wget -O - https://inf-lab.dev/weather/material/scripts/setup.sh | bash
Is the URL now valid? Is the overall usage of the zip manifest API correct?

2025-01-04 19:25 UTC, Kuschel-Swein requested changes

2025-01-04 19:25 UTC, Kuschel-Swein commented on weather/backup-material/weather-service.py
> +@app.route('/', defaults={'city': 'Bamberg'})
I'm not sure if thats the Flask-way to do the default, so should those decorators be merged?

2025-01-04 19:25 UTC, Kuschel-Swein commented on weather/backup-material/bamberg.html
Is this file still needed?

2025-01-04 19:28 UTC, MariusLang commented on weather/backup-material/weather-service.py
> +@app.route('/', defaults={'city': 'Bamberg'})
Yes, thats the way to provide default URL parameters.

2025-01-05 18:49 UTC, Kuschel-Swein requested changes

2025-01-05 18:49 UTC, Kuschel-Swein commented on weather/material/template/weather_service.py
Please use a uniform quotation style.

2025-01-05 18:49 UTC, Kuschel-Swein commented on weather/material/template/weather_service.py
Maybe add some disclaimer that students dont need to understand that file AND create a seperate archive (mention this in task) for it

2025-01-05 19:27 UTC, Kuschel-Swein approved these changes

2025-01-05 19:30 UTC, merged